version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
      PRISMA_SCHEMA_PATH: src/prisma/schema.prisma
    ports:
      - "3000:3000"
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        npx prisma generate --schema=src/prisma/schema.prisma &&
        npx prisma migrate deploy --schema=src/prisma/schema.prisma &&
        node dist/server.js
      "
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
